# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "bootstrap.sh"
  NodeCount = 1
  (1..NodeCount).each do |i|
    config.vm.define "vm0#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.box_check_update = false
      node.vm.hostname = "centosvm0#{i}.local"
      node.vm.network "private_network", ip: "172.16.42.10#{i}"
      node.vm.provider :libvirt do |v|
        v.driver = "kvm"
        v.memory = 2048
        v.cpus = 2
        v.cputopology :sockets => '1', :cores => '2', :threads => '1'
        v.nested = true
      end
      node.vm.provision "shell", inline: <<-SHELL
      timedatectl set-timezone Asia/Kolkata
      shutdown -r now
      SHELL
    end
  end
end
